var date = new Date()

// console.log(date.getDate())
// console.log(date.getDay())
// console.log(date.getFullYear())
// console.log(date.getHours())
// console.log(date.getMilliseconds())
// console.log(date.getTimezoneOffset())
console.log(date.toLocaleDateString())
// console.log(date.setTime(4))
// console.log(date.toLocaleTimeString())
// console.log(date.toDateString())
// console.log(date.toTimeString())
// console.log(date.toLocaleString())
// console.log(date.toString())
// console.log(date)